### ISSUE TITLE
Perl Dependency Check

### ISSUE THREAD

**Issue by noor-codes** [photostructure/exiftool-vendored.exe#3]
# Perl Dependency Check

## Problem
This is a great library to read and write exifdata into image but I ran into an issue.
The code was working fine on my mac but it was not working when deployed into a lightweight alpine os on Docker.

After a lot of debugging, I noticed, `exiftool-vendored` is 99.9% written in perl which was installed by default on my mac but it wasn't on alpine.

All I get was an log of the error but things didn't fail, it should have crushed with a nice error at least.

## Solution
When the user installs this package, it should check if perl is installed or not. This will completely prevent the next person to go through the same issue as me.

Hope this helps 

Thanks

**Comment by noor-codes** [comment]
A good example of this is https://github.com/sass/node-sass which throws error on installation if Python isn't installed on the server / pc

**Comment by mceachen** [comment]
Wrong package: see https://github.com/photostructure/exiftool-vendored.js/issues/152
